version: '3'

services:
  rest-service:
    build: ./rest_service
    expose:
      - 8081
    ports:
      - 8081:8081
    command: python manage.py runserver 0.0.0.0:8081
  frontend-app:
    build:
      context: ./front_app
      args:
        VUE_APP_REST_SERVICE_HOST: "192.168.99.100:8081"
    expose:
      - 8082
    ports:
      - 8082:8082
    command: http-server dist -p 8082 -a 0.0.0.0

